[plugin]
prepend_previewers = [
  { url = "*.jp2", run = "jp2" },
  { url = "*.jpx", run = "jp2" },
  { url = "*.j2k", run = "jp2" },
  { mime = "image/jp2",      run = "jp2" },
  { mime = "image/jpeg2000", run = "jp2" },
  { mime = "image/jpx",      run = "jp2" },
]
prepend_preloaders = [
  { url = "*.jp2", run = "jp2" },
  { url = "*.jpx", run = "jp2" },
  { url = "*.j2k", run = "jp2" },
  { mime = "image/jp2",      run = "jp2" },
  { mime = "image/jpeg2000", run = "jp2" },
  { mime = "image/jpx",      run = "jp2" },
]
